### ISSUE TITLE
If null is passed to staticURL, staticURL.length will throw an error

### ISSUE THREAD

**Issue by gavriguy** [applicaster/client-question-sdk#1]
If null is passed to staticURL, staticURL.length will throw an error and in most cases we recommend to pass `null` as the param

https://github.com/applicaster/client-question-sdk/blob/master/app/url-parameters.js#L5

`let currLocation = (staticURL.length) ? staticURL : window.location.search`

**Comment by yuliroth** [comment]
Fixed
